FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install --omit=dev

COPY package-lock.json ./

COPY . .

RUN npm run build

ENV NODE_ENV=production

EXPOSE 4000

CMD ["node", "dist/server.js"]
