services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: recipme-backend-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/recipme
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:7
    container_name: recipme-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongo_data:
