services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: recipme-backend-dev
    ports:
      - "4000:4000"
    volumes:
      - ../:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/recipme
      - PORT=4000
    depends_on:
      mongodb:
        condition: service_healthy
    command: npm run dev
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4000/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:7
    container_name: recipme-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongo_data_dev:
